

#
# Configure github
#
github:

  # Main features
  features:
    # Enable wiki for documentation
    wiki: true
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: true

  # Buttons
  enabled_merge_buttons:
    # Disable squash button:
    squash: false
    # enable merge button:
    merge: true
    # disable rebase button:
    rebase: false

  # Enable pages publishing
  ghp_branch: gh-pages

  # Testing basic protection of multiple branches,
  # this needs to be tested on the master branch.
  # 
  protected_branches:
  - tristan/test-protected-branch-1
  - tristan/test-protected-branch-2
