image: samthursfield/buildstream:0.1-20170621.1

before_script:
  # Diagnostics
  - mount
  - df -h

  # Work around https://github.com/fedora-cloud/docker-brew-fedora/issues/14
  - export LANG="C.UTF-8"
  - export LC_ALL="C.UTF-8"

  # Store cache in the shared Docker volume
  - export XDG_CACHE_HOME=/cache

# Run premerge commits
#
tests:
  script:
  - python3 setup.py test

# Run integration tests
#
integration_tests:
  script:
    - dnf install -y findutils bzr
    - pip3 install --upgrade .
    - git clone https://gitlab.com/BuildStream/buildstream-tests.git
    - cd buildstream-tests
    - ./run-test.sh test

# Automatically build documentation, only for merges which land
# on master branch.
pages:
  script:
  - pip3 install sphinx
  - pip3 install sphinx-click
  - pip3 install --user -e .
  - make -C doc
  - mv doc/build/html public
  artifacts:
    paths:
    - public/
  only:
  - master
