##
# A Builstream Artifact Server
#
# Spins-up a unnamed and unauthenticated grid:
#  - artifacts server at: http://localhost:50052
#
# BuildStream configuration snippet:
#
#    artifacts:
#      url: http://localhost:50052
#      push: true
#
# Basic usage:
#  - docker-compose -f ci.buildstream-remote-cache.yml up
#  - docker-compose -f ci.buildstream-remote-cache.yml down
#
version: "3.2"

services:
  controller:
    image: buildstream/buildstream:dev
    command: ["bst-artifact-server","--port",
      "50052",
      "--enable-push",
      "/artifacts"
    ]
    ports:
      - 50052:50052
    networks:
      - grid
networks:
  grid:
    driver: bridge

volumes:
  cache:
